apiVersion: batch/v1
kind: Job
metadata:
  name: weather-forecast-fetcher-client
  namespace: weather-forecast
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: weather-forecast-fetcher-client
    spec:
      restartPolicy: Never
      containers:
      - name: weather-forecast-fetcher-client
        image: 192.168.1.101:55000/weather-forecast-fetcher-client:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        args:
        - --ip=fetcher.weather-forecast.svc.cluster.local
        - --port=40000
