apiVersion: batch/v1
kind: Job
metadata:
  name: weather-fetcher-client
  namespace: weather-fetcher-pr-__PLACE_HOLDER_FOR_PR_NUMBER__
spec:
  template:
    metadata:
      labels:
        app: weather-fetcher-client
    spec:
      restartPolicy: Never
      containers:
      - name: weather-fetcher-client
        image: shootingstar.azurecr.io/weather-fetcher-client:pr-__PLACE_HOLDER_FOR_PR_NUMBER__
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        args: 
        - --ip
        - weather-fetcher.weather-fetcher-pr-__PLACE_HOLDER_FOR_PR_NUMBER__.svc.cluster.local
        - --port
        - "50051"
