apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recommender-engine
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: gateway
        image: recommender-engine-gateway:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 50051
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  namespace: recommender-engine
  name: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 50051
  selector:
    app: gateway
