apiVersion: batch/v1
kind: Job
metadata:
  name: weather-forecast-fetcher-client
  namespace: weather-forecast
spec:
  template:
    metadata:
      labels:
        app: weather-forecast-fetcher-client
    spec:
      restartPolicy: Never
      containers:
      - name: weather-forecast-fetcher-client
        image: weather-forecast-fetcher-client:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        args: 
        - --ip
        - fetcher.weather-forecast.svc.cluster.local
        - --port
        - "40000"
