apiVersion: batch/v1
kind: Job
metadata:
  name: recommendation-engine-gateway-client
  namespace: recommendation-engine
spec:
  template:
    metadata:
      labels:
        app: recommendation-engine-gateway-client
    spec:
      restartPolicy: Never
      containers:
      - name: recommendation-engine-gateway-client
        image: recommendation-engine-gateway-client:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        args: 
        - --ip
        - gateway.recommendation-engine.svc.cluster.local
        - --port
        - "50000"
