apiVersion: batch/v1
kind: Job
metadata:
  name: recommendation-engine-profile-client
  namespace: recommendation-engine
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: recommendation-engine-profile-client
    spec:
      restartPolicy: Never
      containers:
      - name: recommendation-engine-profile-client
        image: recommendation-engine-profile-client:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        args: 
        - --ip=profile.recommendation-engine.svc.cluster.local
        - --port="50100"
