apiVersion: batch/v1
kind: Job
metadata:
  namespace: grpc-demo
  name: grpc-client-demo
spec:
  template:
    metadata:
      labels:
        app: grpc-client-demo
    spec:
      restartPolicy: Never
      containers:
      - name: grpc-client-demo
        image: shootingstar.azurecr.io/grpc-client-demo:latest
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        args: 
        - --ip
        - grpc-service-demo.grpc-demo.svc.cluster.local
        - --untrusted-ca
        - --with-http
