apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recommendation-engine
  name: retrieval-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieval-orchestrator
  template:
    metadata:
      labels:
        app: retrieval-orchestrator
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: retrieval-orchestrator
        image: recommendation-engine-retrieval-orchestrator:latest
        imagePullPolicy: Never
        args:
        - --config_path=config.k8s.yaml
        - --host
        - 0.0.0.0
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 50200
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  namespace: recommendation-engine
  name: retrieval-orchestrator
spec:
  type: LoadBalancer
  ports:
  - port: 50200
  selector:
    app: retrieval-orchestrator
