apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recommendation-engine
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: gateway
        image: 192.168.1.101:55000/recommendation-engine-gateway:latest
        imagePullPolicy: IfNotPresent
        args:
        - --profile_service_host=profile.recommendation-engine.svc.cluster.local
        - --profile_service_port=50100
        - --retrieval_service_host=retrieval-orchestrator.recommendation-engine.svc.cluster.local
        - --retrieval_service_port=50200
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 50000
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  namespace: recommendation-engine
  name: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 50000
  selector:
    app: gateway
