name: Weather Fetcher CI
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  K8S_NAMESPACE: weather-fetcher-pr-${{ github.run_number }}
jobs:
  build_and_deploy_weather_fetcher:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code.
      uses: actions/checkout@v4

    - name: Build the image of Weather Fetcher.
      run: |
        ./tools/compile_in_docker.sh //src/weather_fetcher:weather_fetcher
        docker build . --file ./ci_cd/docker_files/weather_fetcher --tag shootingstar.azurecr.io/weather-fetcher:pr-${{ github.run_number }}

    - name: Login to Azure Container Registry.
      uses: Azure/docker-login@v2
      with:
         login-server: shootingstar.azurecr.io
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}

    - name: Push image to Azure Container Registry.
      run: docker push shootingstar.azurecr.io/weather-fetcher:pr-${{ github.run_number }}

    - name: Login as ShootingStarSP.
      uses: Azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up kubectl.
      uses: Azure/setup-kubectl@v4
      with:
        version: v1.30.2

    - name: Set up Kubernetes context.
      uses: Azure/aks-set-context@v4
      with:
         resource-group: ShootingStarRG
         cluster-name: ShootingStarK8s

    - name: Create Kubernetes namespace for current PR.
      run: |
        kubectl create namespace ${{ env.K8S_NAMESPACE }}
        sed -i 's/grpc-demo/${{ env.K8S_NAMESPACE }}/g' manifests/k8s_grpc_service_demo.yaml

    - name: Create Kubernetes secret.
      uses: Azure/k8s-create-secret@v5
      with:
         secret-name: k8s-shootingstar-secret
         namespace: ${{ env.K8S_NAMESPACE }}
         container-registry-url: shootingstar.azurecr.io
         container-registry-username: ${{ secrets.ACR_USERNAME }}
         container-registry-password: ${{ secrets.ACR_PASSWORD }}

    - name: Deploy GrpcServiceDemo to Kubernetes.
      uses: Azure/k8s-deploy@v5
      with:
         action: deploy
         strategy: basic
         namespace: ${{ env.K8S_NAMESPACE }}
         manifests: manifests/k8s_grpc_service_demo.yaml
         images: shootingstar.azurecr.io/grpc-service-demo:pr-${{ github.run_number }}
         imagepullsecrets: k8s-shootingstar-secret

#   test_gprc_service_demo_with_grpc_client_demo:
#     name: test by K8S job
#     runs-on: ubuntu-latest
#     needs: build_and_deploy_grpc_service_demo
#     steps:
#     - name: Checkout the source code.
#       uses: actions/checkout@v4
#
#     - name: Build the image of GrpcClientDemo.
#       run: docker build . --file ./src/GrpcClientDemo/Dockerfile --tag shootingstar.azurecr.io/grpc-client-demo:pr-${{ github.run_number }}
#
#     - name: Login to Azure Container Registry.
#       uses: Azure/docker-login@v2
#       with:
#          login-server: shootingstar.azurecr.io
#          username: ${{ secrets.ACR_USERNAME }}
#          password: ${{ secrets.ACR_PASSWORD }}
#
#     - name: Push image to Azure Container Registry.
#       run: docker push shootingstar.azurecr.io/grpc-client-demo:pr-${{ github.run_number }}
#
#     - name: Login as ShootingStarSP.
#       uses: Azure/login@v2
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#     - name: Set up kubectl.
#       uses: Azure/setup-kubectl@v4
#       with:
#         version: v1.30.2
#
#     - name: Set up Kubernetes context.
#       uses: Azure/aks-set-context@v4
#       with:
#          resource-group: ShootingStarRG
#          cluster-name: ShootingStarK8s
#
#     - name: Create Kubernetes secret.
#       uses: Azure/k8s-create-secret@v5
#       with:
#          secret-name: k8s-shootingstar-secret
#          namespace: ${{ env.K8S_NAMESPACE }}
#          container-registry-url: shootingstar.azurecr.io
#          container-registry-username: ${{ secrets.ACR_USERNAME }}
#          container-registry-password: ${{ secrets.ACR_PASSWORD }}
#
#     - name: Set Kubernetes namespace for current PR.
#       run: |
#         sed -i 's/grpc-demo/${{ env.K8S_NAMESPACE }}/g' manifests/k8s_grpc_client_demo.yaml
#
#     - name: Create Kubernetes job of GrpcClientDemo.
#       uses: Azure/k8s-deploy@v5
#       with:
#          action: deploy
#          strategy: basic
#          namespace: ${{ env.K8S_NAMESPACE }}
#          manifests: manifests/k8s_grpc_client_demo.yaml
#          images: shootingstar.azurecr.io/grpc-client-demo:pr-${{ github.run_number }}
#          imagepullsecrets: k8s-shootingstar-secret
#
#     - name: Test by Kubernetes job of GrpcClientDemo.
#       run: |
#         sleep 15s
#         bash ./tools/check_grpc_client_response.sh "${{ env.K8S_NAMESPACE }}" 'grpc-client-demo' 'Greeting: Hello World'
